This Notebook is do data preprocessing and Machine Learning Model traning on data.
Below is the code that load libraries

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import joblib

dataFile = pd.read_csv("ProcessedCSVStrokData.csv")
dataFile.head()

,Age,Gender,SES,Hypertension,Heart_Disease,BMI,Avg_Glucose,Diabetes,Smoking_Status,Stroke,gender_map,SES_map,Smoking_Status_map
0,0.544988,Male,Medium,1,0,0.332878,0.389395,1,Current,1,1,1,2
1,0.818384,Female,Medium,1,1,0.538945,0.672076,0,Never,1,0,1,0
2,0.675658,Female,Medium,1,0,0.790045,0.504706,0,Never,0,0,1,0
3,0.624331,Female,Low,0,1,0.553491,0.613447,0,Former,0,0,0,1
4,0.448678,Male,Low,0,0,0.339653,0.594506,1,Never,1,1,0,0

Task 1, Statistical Analysis

In [3]:
dataFile.describe()

,Age,Hypertension,Heart_Disease,BMI,Avg_Glucose,Diabetes,Stroke
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,69.757847,0.605800,0.302800,28.042252,109.115918,0.196000,0.297800
std,9.869468,0.488703,0.459492,4.901424,16.421142,0.396988,0.457314
min,27.706561,0.000000,0.000000,15.037988,45.569135,0.000000,0.000000
25%,63.128574,0.000000,0.000000,24.660786,98.188349,0.000000,0.000000
50%,69.796042,1.000000,0.000000,28.066932,109.022208,0.000000,0.000000
75%,76.402885,1.000000,1.000000,31.390170,120.341179,0.000000,1.000000
max,99.417448,1.000000,1.000000,47.495955,176.180688,1.000000,1.000000

Checked The data types of all the coulmns of CSV file

In [4]:
dataFile.dtypes

Age               float64
Gender             object
SES                object
Hypertension        int64
Heart_Disease       int64
BMI               float64
Avg_Glucose       float64
Diabetes            int64
Smoking_Status     object
Stroke              int64
dtype: object

Checking the correlation of columns with each other

In [5]:
# Numeric columns correlation
dataFile.corr(numeric_only=True)

,Age,Hypertension,Heart_Disease,BMI,Avg_Glucose,Diabetes,Stroke
Age,1.000000,0.417468,0.109534,-0.001319,0.138313,0.132659,0.362514
Hypertension,0.417468,1.000000,0.051501,-0.003692,0.308235,0.058061,0.388837
Heart_Disease,0.109534,0.051501,1.000000,-0.002336,0.297635,0.022211,0.274265
BMI,-0.001319,-0.003692,-0.002336,1.000000,0.005738,-0.003925,0.083252
Avg_Glucose,0.138313,0.308235,0.297635,0.005738,1.000000,0.009723,0.220624
Diabetes,0.132659,0.058061,0.022211,-0.003925,0.009723,1.000000,0.248065
Stroke,0.362514,0.388837,0.274265,0.083252,0.220624,0.248065,1.000000

Checking the Null values

In [6]:
dataFile.isna().sum()

NameError: name 'dataFile' is not defined

In [8]:
dataFile['Age']=(dataFile['Age']-dataFile['Age'].min())/(dataFile['Age'].max()-dataFile['Age'].min())
dataFile['BMI']=(dataFile['BMI']-dataFile['BMI'].min())/(dataFile['BMI'].max()-dataFile['BMI'].min())
dataFile['Avg_Glucose']=(dataFile['Avg_Glucose']-dataFile['Avg_Glucose'].min())/(dataFile['Avg_Glucose'].max()-dataFile['Avg_Glucose'].min())
dataFile.to_csv('ProcessedCSVStrokData.csv', index=False)

In [3]:
dataFile=pd.read_csv('ProcessedCSVStrokData.csv')
dataFile.head()

,Age,Gender,SES,Hypertension,Heart_Disease,BMI,Avg_Glucose,Diabetes,Smoking_Status,Stroke,gender_map,SES_map,Smoking_Status_map
0,0.544988,Male,Medium,1,0,0.332878,0.389395,1,Current,1,1,1,2
1,0.818384,Female,Medium,1,1,0.538945,0.672076,0,Never,1,0,1,0
2,0.675658,Female,Medium,1,0,0.790045,0.504706,0,Never,0,0,1,0
3,0.624331,Female,Low,0,1,0.553491,0.613447,0,Former,0,0,0,1
4,0.448678,Male,Low,0,0,0.339653,0.594506,1,Never,1,1,0,0

Data Encoding Phase
Gender, Residence_type and smoking_status are need to be encoded for training of machine learning model effecively.

In [4]:
dataFile['gender_map']=dataFile['Gender'].map({
    "Female" :0 ,
    "Male":1,
    "Other":2
})

In [5]:
dataFile['SES_map']=dataFile['SES'].map({
    "Low":0 ,
    "Medium":1,
    "High":2
})

In [6]:
dataFile['Smoking_Status_map']=dataFile['Smoking_Status'].map({
    "Never":0,
    "Former":1,
    "Current":2,
})

In [5]:
dataFile.to_csv('ProcessedCSVStrokData.csv', index=False)

NameError: name 'dataFile' is not defined

In [4]:
dataFile=dataFile=pd.read_csv('ProcessedCSVStrokData.csv')
dataFile.head()

NameError: name 'pd' is not defined

Data Preprocessing Is complete, now save the file and display the head

In [3]:
dataFile.to_csv('ProcessedCSVStrokData.csv', index=False)
dataFile.head()

NameError: name 'dataFile' is not defined

Setting th data for train and test spliting

In [8]:
X=dataFile[['Age', 'Hypertension', 'Heart_Disease', 'Avg_Glucose', 'BMI','gender_map', 'SES_map', 'Smoking_Status_map' ]]
Y=dataFile['Stroke']
X.head()

,Age,Hypertension,Heart_Disease,Avg_Glucose,BMI,gender_map,SES_map,Smoking_Status_map
0,0.544988,1,0,0.389395,0.332878,1,1,2
1,0.818384,1,1,0.672076,0.538945,0,1,0
2,0.675658,1,0,0.504706,0.790045,0,1,0
3,0.624331,0,1,0.613447,0.553491,0,0,1
4,0.448678,0,0,0.594506,0.339653,1,0,0

In [9]:
dataFile['Stroke'].value_counts()

Stroke
0    7022
1    2978
Name: count, dtype: int64

Test Train splitting the data, we divide our data into test and train portion, so we can train and test the model

In [14]:
X_train, X_test, Y_train, Y_test=train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [15]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

Initializing Models

In [35]:
models={
    "DecisionTree": DecisionTreeClassifier(random_state=42,class_weight='balanced'),
    "RandomForest":RandomForestClassifier(random_state=42,class_weight='balanced'),
    "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42,class_weight='balanced'),
    "SVM": SVC(random_state=42,class_weight='balanced'),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),

    "XGBoost": XGBClassifier(random_state=42,eval_metric='logloss')}

Trainning, testing and evaluating the model

In [38]:
results={}
for name, model in models.items():
    if name in ['LogisticRegression', 'SVM']:
        model.fit(X_train_scaled, Y_train)
        y_predictions=model.predict(X_test_scaled)
    else:
        model.fit(X_train, Y_train)
        y_predictions=model.predict(X_test)

    results[name] = {
        "Precision_score": precision_score(Y_test, y_predictions),
        "Recall_score": recall_score(Y_test, y_predictions),
        "Accuracy_score": accuracy_score(Y_test, y_predictions),
        "F1_score": f1_score(Y_test, y_predictions)
    }

results_df=pd.DataFrame(results).T
results_df

                    Precision_score  Recall_score  Accuracy_score  F1_score
DecisionTree               0.482877      0.480409          0.6965  0.481640
RandomForest               0.613909      0.436116          0.7540  0.509960
LogisticRegression         0.514019      0.749574          0.7185  0.609841
SVM                        0.523810      0.749574          0.7265  0.616678
GradientBoosting           0.682927      0.429302          0.7740  0.527197
XGBoost                    0.618182      0.463373          0.7585  0.529698

In [ ]:
for name, model in models.items():
    if name=='SVM':
        model.fit(X_train_scaled, Y_train)
        y_predictions=model.predict(X_test_scaled)
        joblib.dump(model, "best_model_SVM.pkl")
        joblib.dump(scaler, "scaler_SVM.pkl")
print("✅ Model and scaler saved successfully")

     Precision_score  Recall_score  Accuracy_score  F1_score
SVM          0.52381      0.749574          0.7265  0.616678